/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WavePortalAbi } from "./WavePortalAbi";

export { WavePortalAbi__factory } from "./factories/WavePortalAbi__factory";
